### PR TITLE
Introduced a simple test client that enables easier unit testing

### PR DESCRIPTION
**Pull request by Toflar**
Hey everybody,

I noticed that the library and the bundle have no unit tests but apparently it's also autogenerated. So I'm not sure about your stance on testing but it's very important to me. As this bundle generates services depending on the config I found it a bit hard to mock the different services. Mocking in unit tests is actually doable but when working on functional tests it's really hard. So I came up with this simple solution. You can now configure the bundle as follows for your test environment:

```yaml
sendinblue_api:
    endpoints:
        - smtp
    key: '%env(SENDINBLUE_API_KEY)%'
    test: true # Enable test mode
```

It will just swap the underlying `ApiClient` and override the `callApi()` method in such a way that the calls are just "recorded" in an array instead of being executed for real. This allows to easily integrate it e.g. in Behat tests and analyze the recorded requests like so:

```php
$testClient = $this->SMTPApi->getApiClient();

if (!$testClient instanceof \SendinBlue\Bundle\ApiBundle\Client\TestClient) {
    throw new \RuntimeException('API client must be an instance of TestClient to allow testing.');
}

// Use $testClient->getRecordedCalls() to compare to your expectations
```

Thanks for your feedback!

### CODE REVIEW

**Comment by MatTheCat** [comment]
Given how it is trivial to override services based on the environment or mocking services in Symfony I'm not sure we need to include a default test client 🤔

**Comment by Toflar** [comment]
I just need to do it for every endpoint and this in every project. I find it easier to just enable the test mode ;-) But the test client class should go into the library but this one seems autogenerated and untested completely so not sure how you guys want to proceed there.

**Comment by MatTheCat** [comment]
All client definitions inherit `sendinblue_api.client` so you just have to override it on your test environment.

I don't think we'll provide a default test client.

**Comment by Toflar** [comment]
Okay, I don't think it's a good decision but I'll just add it to my project then. Thanks for taking the time to reply!

**Comment by elhayadi** [comment]
1- use statements:

```
use SendinBlue\Client\Configuration;
use SendinBlue\Client\Api\AccountApi;
use SendinBlue\Client\ApiClient;
use SendinBlue\Client\Api\SMTPApi;
use SendinBlue\Client\Model\SendSmtpEmail;
```

2- send simple email:
```
$config = Configuration::getDefaultConfiguration()->setApiKey('api-key', 'YOUR_API_KEY');

        $apiInstance = new SMTPApi(
            // If you want use custom http client, pass your client which implements `GuzzleHttp\ClientInterface`.
            // This is optional, `GuzzleHttp\Client` will be used as default.
            new ApiClient(),
            $config
        );
       // string | Unique id of the transactional email that has been sent to a particular contact
        $sendSmtpEmail = new SendSmtpEmail(); // \SendinBlue\Client\Model\SendSmtpEmail | Values to send a transactional email
        $sendSmtpEmail['to'] = array(array('email'=>'elhayadi999@gmail.com', 'name'=>'mohamed elhayadi'));
        $sendSmtpEmail['templateId'] = 3;// you should create a template in sendinblue and get her the id 
        $date =new DateTime();
        $sendSmtpEmail['params'] = array(
            'NUM_RESERVATION'=>166458,
            'DEBUT_RESERVATION'=>$date, 
            'FIN_RESERVATION'=>$date, 
            'PLAGE'=>"12:00 à 14:00", 
            'Payed'=>true,
            'NBR_HEURES'=> 2, 
            'NOM'=>"elhayadi", 
            'PRENOM'=> "mohamed",
            'FUSEAU_HORAIRE'=>"PARIS");
        try {
            $result = $apiInstance->sendTransacEmail($sendSmtpEmail);
       
            print_r($result);
        } catch (Exception $e) {
            echo 'Exception when calling TransactionalEmailsApi->getTransacEmailContent: ', $e->getMessage(), PHP_EOL;
        }
```

**Pull request closed without merging**
